sudo: required
services : 
  - docker

before_install :
  - docker build -t aniketshukla/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aniketshukla/docker-react npm run test -- --coverage